// Quotes for the calendar app
// Extracted from QUOTES.md

export const QUOTES = [
  ""Everything is naturally pure from the beginning." — Longchen Rabjam (Longchenpa)",
  ""In the expanse of awareness, there is nothing to correct." — Longchen Rabjam (Longchenpa)",
  ""The nature of mind is empty, luminous, and free." — Longchen Rabjam (Longchenpa)",
  ""All phenomena arise as the display of awareness." — Longchen Rabjam (Longchenpa)",
  ""Rest in the uncontrived nature, beyond effort." — Longchen Rabjam (Longchenpa)",
  ""Since the ground is primordially pure, there is nothing to abandon." — Longchen Rabjam (Longchenpa)",
  ""Awareness is self-arisen and self-liberated." — Longchen Rabjam (Longchenpa)",
  ""In rigpa, there is no duality of samsara and nirvana." — Longchen Rabjam (Longchenpa)",
  ""Appearances and emptiness are inseparable." — Longchen Rabjam (Longchenpa)",
  ""Leave mind in its natural state, without fabrication." — Longchen Rabjam (Longchenpa)",
  ""Do not follow the past. Do not anticipate the future." — Jigme Lingpa",
  ""Remain in the freshness of unfabricated awareness." — Jigme Lingpa",
  ""Thoughts liberate themselves as they arise." — Jigme Lingpa",
  ""The nature of mind is primordially free." — Jigme Lingpa",
  ""Whatever arises is the ornament of awareness." — Jigme Lingpa",
  ""Rest without grasping, in the natural flow." — Jigme Lingpa",
  ""Emptiness is not nothingness; it is openness." — Jigme Lingpa",
  ""Rigpa is present, needing no search." — Jigme Lingpa",
  ""Let everything be as it is, in naturalness." — Jigme Lingpa",
  ""Mind itself is the Buddha, if recognized." — Jigme Lingpa",
  ""Rest in natural great peace, this exhausted mind." — Nyoshul Khenpo Rinpoche",
  ""Thoughts are like clouds; awareness is the sky." — Nyoshul Khenpo Rinpoche",
  ""Do not meditate, do not be distracted." — Nyoshul Khenpo Rinpoche",
  ""Simply remain in the state of rigpa." — Nyoshul Khenpo Rinpoche",
  ""Nothing needs to be changed; only recognized." — Nyoshul Khenpo Rinpoche",
  ""Everything is already complete in the nature of mind." — Nyoshul Khenpo Rinpoche",
  ""The essence of Dzogchen is simplicity." — Nyoshul Khenpo Rinpoche",
  ""Awareness is naked, fresh, and free." — Nyoshul Khenpo Rinpoche",
  ""Do not seek elsewhere what is already within." — Nyoshul Khenpo Rinpoche",
  ""Let go into the vastness of being." — Nyoshul Khenpo Rinpoche",
  ""Do not be distracted. This is the essence of the practice." — Patrul Rinpoche",
  ""Mind, left as it is, is the Buddha." — Patrul Rinpoche",
  ""The view is Longchenpa; the practice is Patrul." — Patrul Rinpoche",
  ""Everything is mind; mind is empty." — Patrul Rinpoche",
  ""Rest naturally, without altering anything." — Patrul Rinpoche",
  ""Do not cling even to meditation." — Patrul Rinpoche",
  ""Let thoughts arise and dissolve by themselves." — Patrul Rinpoche",
  ""The root of practice is renunciation and devotion." — Patrul Rinpoche",
  ""Awareness itself is the teacher." — Patrul Rinpoche",
  ""Nothing is hidden from rigpa." — Patrul Rinpoche",
  ""Do not look for the Buddha elsewhere; your own mind is the Buddha." — Dilgo Khyentse Rinpoche",
  ""The essence of the teaching is to tame the mind." — Dilgo Khyentse Rinpoche",
  ""Meditation is simply resting in awareness." — Dilgo Khyentse Rinpoche",
  ""The nature of mind is always present, like the sky." — Dilgo Khyentse Rinpoche",
  ""When you let go, everything opens." — Dilgo Khyentse Rinpoche",
  ""Rigpa is not something to create, only to recognize." — Dilgo Khyentse Rinpoche",
  ""In the true nature, there is nothing to improve." — Dilgo Khyentse Rinpoche",
  ""Whatever arises is the play of emptiness and clarity." — Dilgo Khyentse Rinpoche",
  ""Do not be caught by concepts; return to awareness." — Dudjom Rinpoche",
  ""Everything is the display of rigpa." — Dudjom Rinpoche",
  ""Primordial purity is the nature of all beings." — Dudjom Rinpoche",
  ""Let go of what has passed, let go of what may come, let go of what is happening now." — Tilopa",
  ""Do not think, do not meditate, do not analyze; rest in the natural state." — Tilopa",
  ""Mind without grasping is Mahāmudrā." — Tilopa",
  ""Appearances are mind, and mind is empty." — Tilopa",
  ""Rest relaxed in the uncontrived." — Tilopa",
  ""Cut through doubt with certainty in awareness." — Naropa",
  ""Thoughts arise like waves and dissolve back into the ocean." — Naropa",
  ""The nature of mind is clear light." — Naropa",
  ""Do not seek the mind; rest in mind itself." — Naropa",
  ""Without fixation, everything liberates." — Naropa",
  ""The essence of Mahāmudrā is simplicity." — Saraha",
  ""Mind has no form, yet it knows." — Saraha",
  ""Freedom is not elsewhere; it is recognizing what is." — Saraha",
  ""Let mind rest in its own place." — Maitripa",
  ""Nonmeditation is the supreme meditation." — Maitripa",
  ""Do not fabricate; the natural state is enough." — Maitripa",
  ""The mind's nature is empty, luminous, and aware." — Maitripa",
  ""Do not alter awareness; simply know it." — Maitripa",
  ""Mind itself, uncontrived, is the Buddha." — Gampopa",
  ""The root of meditation is devotion to the guru." — Gampopa",
  ""Through knowing mind, all is known." — Gampopa",
  ""Let mind settle naturally, without grasping." — Gampopa",
  ""All phenomena are the mind's display." — Gampopa",
  ""The ordinary mind is the path." — Gampopa",
  ""In the simplicity of mind, there is liberation." — Gampopa",
  ""Do not chase thoughts; let them vanish by themselves." — Dakpo Tashi Namgyal",
  ""Awareness is empty, yet cognizant." — Dakpo Tashi Namgyal",
  ""Meditation is resting without distraction." — Dakpo Tashi Namgyal",
  ""The essence is to recognize mind's nature." — Dakpo Tashi Namgyal",
  ""Clinging is the root of samsara." — Dakpo Tashi Namgyal",
  ""Nothing needs to be removed; nothing needs to be added." — The 9th Karmapa, Wangchuk Dorje",
  ""Recognize your own mind, and you will be free." — The 9th Karmapa, Wangchuk Dorje",
  ""Mind's nature is beyond coming and going." — The 9th Karmapa, Wangchuk Dorje",
  ""Rest evenly, without acceptance or rejection." — The 9th Karmapa, Wangchuk Dorje",
  ""Mahāmudrā is not made; it is discovered." — The 9th Karmapa, Wangchuk Dorje",
  ""The nature of mind is clarity inseparable from emptiness." — The 16th Karmapa, Rangjung Rigpe Dorje",
  ""Nothing is more important than knowing your own mind." — The 16th Karmapa, Rangjung Rigpe Dorje",
  ""Let mind rest as it is, like a mountain." — The 16th Karmapa, Rangjung Rigpe Dorje",
  ""Compassion and emptiness are inseparable." — The 17th Karmapa, Ogyen Trinley Dorje",
  ""Meditation is familiarity with the mind's nature." — The 17th Karmapa, Ogyen Trinley Dorje",
  ""Awareness is present before thought." — The 17th Karmapa, Ogyen Trinley Dorje",
  ""In resting naturally, wisdom dawns." — Milarepa",
  ""My religion is to live and die without regret." — Milarepa",
  ""In the sky of mind, clouds of thought dissolve." — Milarepa",
  ""Without attachment, there is no fear." — Milarepa",
  ""Do not look outside; look within." — Milarepa",
  ""The songs of realization arise from simplicity." — Milarepa",
  ""Devotion is the gateway to Mahāmudrā." — Jamgön Kongtrül Lodrö Thayé",
  ""The mind's nature is the union of clarity and emptiness." — Jamgön Kongtrül Lodrö Thayé",
  ""Rest in awareness, free from effort." — Jamgön Kongtrül Lodrö Thayé",
  ""Mahāmudrā is the direct path of seeing mind itself." — Jamgön Kongtrül Lodrö Thayé",
];

export const getRandomQuote = (): string => {
  const randomIndex = Math.floor(Math.random() * QUOTES.length);
  return QUOTES[randomIndex];
};
