// Kalapa daily contemplation quotes, all by Sakyong Mipham Rinpoche.
// Transcribed from assets/New Kalapa Quotations/*.jpeg (sakyong.com daily contemplations export).

export const KALAPA_QUOTES = [
  "\"Bodhichitta is the lightest mind we could have, because it is no longer burdened by the concept of 'me.'\" — Sakyong Mipham Rinpoche",
  "\"Compassion and love have no limit, especially if we encourage their growth with the practice of stepping beyond ourselves.\" — Sakyong Mipham Rinpoche",
  "\"Living wisely means doing what the mind naturally yearns to do—extend itself to others with kindness and care.\" — Sakyong Mipham Rinpoche",
  "\"With consistent practice we learn to connect continually to the mind's clarity and the heart's warmth—no matter what happens.\" — Sakyong Mipham Rinpoche",
  "\"We can use bodhichitta practice to counteract aggression, beginning with our own.\" — Sakyong Mipham Rinpoche",
  "\"The crowning jewel of the heart and mind is the ability to extend love and compassion. Love means that we want others to experience happiness. Compassion means that we wish them not to suffer.\" — Sakyong Mipham Rinpoche",
  "\"If we have compassion and love for everyone, beyond the concept of friend and enemy, all our wishes will be fulfilled.\" — Sakyong Mipham Rinpoche",
  "\"Regard all sentient beings as your mother.\" — Sakyong Mipham Rinpoche",
  "\"Bodhichitta gives us the opportunity to weave the tapestry of happiness every day with the needle and thread of our own mind.\" — Sakyong Mipham Rinpoche",
  "\"I always try to have a contemplation going. This can be as simple as bringing my mind back to the thought 'May others be happy' at every opportunity.\" — Sakyong Mipham Rinpoche",
  "\"Generate loving-kindness.\" — Sakyong Mipham Rinpoche",
  "\"If our intention is to help others—even if we are unable to follow it through—we will never have any regret.\" — Sakyong Mipham Rinpoche",
  "\"You need to eat well, sleep well, and have a roof over your head, but don't go much further than that before extending yourself to others.\" — Sakyong Mipham Rinpoche",
  "\"The love and compassion beneath the clutter of negativity are natural and permanent.\" — Sakyong Mipham Rinpoche",
  "\"Think of the kindness of others.\" — Sakyong Mipham Rinpoche",
  "\"Uproot negativity by contemplating the suffering of others.\" — Sakyong Mipham Rinpoche",
  "\"True love is the natural energy of our settled mind, an inexhaustible resource.\" — Sakyong Mipham Rinpoche",
  "\"Contemplating love gives us the biggest of minds. The farther our love extends, the bigger our heart grows.\" — Sakyong Mipham Rinpoche",
  "\"Love mixed with space is called letting go.\" — Sakyong Mipham Rinpoche",
  "\"Thinking about how to help others relieves stress, brings joy, and has fantastic karmic repercussions.\" — Sakyong Mipham Rinpoche",
  "\"The sun shines, whether it is day or night, and so should our concern for others.\" — Sakyong Mipham Rinpoche",
  "\"We all love to be in love, because deep inside we love caring for others.\" — Sakyong Mipham Rinpoche",
  "\"Bodhichitta is the radiant heart that is constantly and naturally, without self-consciousness, generates love and compassion for the benefit of others.\" — Sakyong Mipham Rinpoche",
  "\"Bodhichitta is a stream of love and compassion that connects us all, without fixation or attachment.\" — Sakyong Mipham Rinpoche",
  "\"In contemplating bodhichitta, we're learning to make unconditional love our basic motivation.\" — Sakyong Mipham Rinpoche",
  "\"Rousing bodhichitta propels us to start giving rather than keep taking.\" — Sakyong Mipham Rinpoche",
  "\"Bodhichitta is a free-flowing energy that connects us with everyone, beyond the limitations of personalities and concepts.\" — Sakyong Mipham Rinpoche",
  "\"If we are diligent in generating love and compassion, eventually it will spontaneously arise in any situation.\" — Sakyong Mipham Rinpoche",
  "\"Rousing bodhichitta is jumping into the heart of enlightenment, which is the same as our own.\" — Sakyong Mipham Rinpoche",
  "\"Bodhichitta is not simply what we have, it is what we are.\" — Sakyong Mipham Rinpoche",
  "\"Rather than trying to change everything at once, work with changing a small percentage of your attitude for a small percentage of the day. When you get up in the morning, say, 'With ten percent of my mind, I'm going to try peace instead of irritation.'\" — Sakyong Mipham Rinpoche",
  "\"Every time you think of someone else's happiness, you are taking a vacation from the 'me' plan.\" — Sakyong Mipham Rinpoche",
  "\"Playing the game of ten percent means slowing down, stepping back, and asking, What is my view? Am I fearless with wisdom, ready to help others? Or am I fearless with ignorance, ready to indulge in negativity?\" — Sakyong Mipham Rinpoche",
  "\"When we churn 'What about me?' into 'What about you?' we are consciously changing our molecular structure by engaging the big-mind chromosome. The result is ziji—radiant inner confidence.\" — Sakyong Mipham Rinpoche",
  "\"Using a small part of each day for formal meditation practice, we begin to discover the inherent joy, liberation, and power that lie at our fingertips, the explosive wisdom that gives the Buddha a ten-foot halo.\" — Sakyong Mipham Rinpoche",
  "\"There are only a small number of people meditating, even on a global scale. If we have the inspiration and courage to say, 'It's up to me to bring peace,' our influence will be larger than our numbers.\" — Sakyong Mipham Rinpoche",
  "\"Specifically wishing happiness for people you don't like can make them easier to deal with. Keep a list of people you are angry with. As you work your way through the list, you will find it becoming easier to forgive.\" — Sakyong Mipham Rinpoche",
  "\"Upon awakening in the morning, contemplate this thought, 'Just as I have awakened, may all sentient beings awaken from the sleep of ignorance.'\" — Sakyong Mipham Rinpoche",
  "\"While dressing, contemplate this thought, 'May all sentient beings wear the clothing of respect for others and for themselves.'\" — Sakyong Mipham Rinpoche",
  "\"In any activity, you can take this view, 'If I'm not to become a buddha right away, may I please be in a situation where I can be of some benefit to sentient beings.'\" — Sakyong Mipham Rinpoche",
  "\"Look in the bathroom mirror every morning and repeat three times, 'It's not about me.'\" — Sakyong Mipham Rinpoche",
  "\"If you place your mind on thoughts that are based upon compassion and wisdom, that's what the mind will become familiar with. Then like any habit, thinking of wisdom and compassion will increase.\" — Sakyong Mipham Rinpoche",
  "\"Changing your attitude is the way to effect change in your life.\" — Sakyong Mipham Rinpoche",
  "\"When we meditate, we're training ourselves to see our weak points and strengthen our positive ones.\" — Sakyong Mipham Rinpoche",
  "\"When we meditate, we're altering our basic perception. We're beginning to change how we relate to the world. But we have to be willing to change.\" — Sakyong Mipham Rinpoche",
  "\"Use the mindfulness and awareness you develop on the cushion to stay in the saddle of your life. Can you appreciate these fruits of practice without expectation or attachment?\" — Sakyong Mipham Rinpoche",
  "\"Meditating slowly unravels our root fantasy: 'I' am real and there's a way to make 'me' happy.\" — Sakyong Mipham Rinpoche",
  "\"Working steadily with wild chatter in meditation makes it easier to maintain mindfulness throughout the day.\" — Sakyong Mipham Rinpoche",
  "\"If you forget what you're doing with your mind, almost inevitably you also forget what you're doing with your body.\" — Sakyong Mipham Rinpoche",
  "\"Each time you return to the breath, you're taking one step away from addiction to discursiveness and fear and one step forward on the path of enlightenment.\" — Sakyong Mipham Rinpoche",
  "\"The sensible approach is to say, 'I can still be irritated ninety percent of the time. But with ten percent of my mind and heart, I'll try putting others first.'\" — Sakyong Mipham Rinpoche",
  "\"Contemplating love and compassion, karma and samsara, the preciousness of being human, or the inevitability of death, is a way of diving deep into truth and awakening our wisdom.\" — Sakyong Mipham Rinpoche",
  "\"When you feel that things are falling apart, contemplate the preciousness of human birth. Let your mind rest in a sense of appreciation for life.\" — Sakyong Mipham Rinpoche",
  "\"When you feel that you are making emotions and thoughts solid, contemplate impermanence as a reminder that all is in flux.\" — Sakyong Mipham Rinpoche",
  "\"When you are in the throes of an intense situation, contemplate the nature of samsara instead of feeling that you are completely to blame.\" — Sakyong Mipham Rinpoche",
  "\"When you are in the grips of anger or desire, contemplate and dismantle the emotion by investigating it. Where did this feeling come from? Where is it dwelling?\" — Sakyong Mipham Rinpoche",
  "\"By looking to find someone else to blame, we are failing to deal with our own mind.\" — Sakyong Mipham Rinpoche",
  "\"Little mind becomes smaller with bad habits. Big mind becomes bigger with good ones.\" — Sakyong Mipham Rinpoche",
  "\"Instead of having a hundred thoughts about 'me,' try having at least thirty about others.\" — Sakyong Mipham Rinpoche",
  "\"The more you help others, the more soft and fertile your heart becomes.\" — Sakyong Mipham Rinpoche",
  "\"Knowing what to do is not enough; we have to do it.\" — Sakyong Mipham Rinpoche",
  "\"The path of meditation isn't necessarily about becoming a Buddhist. It's about awakening to who we already are: buddha—'awakened one.'\" — Sakyong Mipham Rinpoche",
  "\"Through peaceful abiding, we learn to rest fearlessly in our natural state, which is basic goodness.\" — Sakyong Mipham Rinpoche",
  "\"We experience basic goodness when we relax deeply into how things are, without wanting to change them. This is why we meditate.\" — Sakyong Mipham Rinpoche",
  "\"A successful meditation practice is a consistent practice. Ten to twenty minutes of sitting practice a couple of times daily over a lifetime is good.\" — Sakyong Mipham Rinpoche",
  "\"In the practice of meditation, we learn to zoom back and get a bigger perspective, rather than always thinking so small.\" — Sakyong Mipham Rinpoche",
  "\"Meditation offers direct experience of the Buddha's discovery that suffering comes from misunderstanding the self as a solid entity. This prepares us for the real possibility of encountering our own basic goodness.\" — Sakyong Mipham Rinpoche",
  "\"Practicing peaceful abiding is an opportunity to take a vacation from acting on the speed and vibration of the mind.\" — Sakyong Mipham Rinpoche",
  "\"By practicing peaceful abiding together, we're establishing a culture based on the foundation that each of us has the genes for enlightenment.\" — Sakyong Mipham Rinpoche",
  "\"In meditation we see how clinging to the illusion of solidity causes suffering.\" — Sakyong Mipham Rinpoche",
  "\"Meditation is training the mind not to fixate.\" — Sakyong Mipham Rinpoche",
  "\"In sitting meditation, we develop the patience and honesty to be self-aware.\" — Sakyong Mipham Rinpoche",
  "\"Whether or not we are working with our mind in formal meditation, we are always working with our mind. Most of the time we're using it to meditate on 'me.'\" — Sakyong Mipham Rinpoche",
  "\"In practicing meditation we rejoice in the possibility of developing a clear view of the facts of life, an unconditionally loving heart, and the wisdom to know the right thing to do always.\" — Sakyong Mipham Rinpoche",
  "\"Meditation is the best preparation for working in a world where we are increasingly pressed into each other's faces. By engaging our mind on the cushion, we learn to work with our own reactivity.\" — Sakyong Mipham Rinpoche",
  "\"The practice of meditation creates the psychological space in which to choose our responses off the cushion.\" — Sakyong Mipham Rinpoche",
  "\"It may look as if we're doing nothing on the cushion, but in fact we're cultivating peace. From that point of view, the practice of meditation is a courageous activity.\" — Sakyong Mipham Rinpoche",
  "\"If we can learn to relax our discursive mind, we will find that underneath it all, we are already happy.\" — Sakyong Mipham Rinpoche",
  "\"Sitting still in meditation is not something we do just once in order to solve our problems. We need to do it consistently, like drinking water and eating food.\" — Sakyong Mipham Rinpoche",
  "\"Conflict and aggression are ancient issues, and so is the dilemma of dealing with the mind. Like Buddha Shakyamuni, we can use what we discover in meditation to help the world move forward.\" — Sakyong Mipham Rinpoche",
  "\"Even though we may think that we don't meditate, we are always meditating on something, developing a view or attitude that helps build the foundation for our actions.\" — Sakyong Mipham Rinpoche",
  "\"In meditation we begin to get a glimpse of the vast tranquility, clarity, and steadiness that underlies all the mental drama. These are qualities of good mind.\" — Sakyong Mipham Rinpoche",
  "\"Sitting meditation gives us the confidence to be able to acknowledge our thoughts without being hooked by them.\" — Sakyong Mipham Rinpoche",
  "\"In meditation, we are putting the mind into a situation where it can become flexible, joyous, and less of a problem. It's that simple.\" — Sakyong Mipham Rinpoche",
  "\"Without the ability to rule our thoughts, we are seduced or abducted by every whim that walks through the door.\" — Sakyong Mipham Rinpoche",
  "\"When we sit correctly, the body can relax and be less of a nuisance to the mind. At the same time, connecting with the mind's natural stability and space invigorates the body, like breathing fresh air.\" — Sakyong Mipham Rinpoche",
  "\"For dealing with the rigors of life, the mind of meditation is a wonderful ally.\" — Sakyong Mipham Rinpoche",
  "\"If we don't become familiar with the inherent stability of the mind, there won't ever be anything interesting about coming back to the present moment.\" — Sakyong Mipham Rinpoche",
  "\"Peaceful abiding is a practice of noticing how the mind vibrates—how it creates story, speed, and solidity—and learning how to tune it to the present moment.\" — Sakyong Mipham Rinpoche",
  "\"Meditation allows us to relax our grip on 'me' because we're able to see thoughts not as our personal identity, but as the effects of our speeding mind.\" — Sakyong Mipham Rinpoche",
  "\"Experiencing the stability and joy of our mind eventually becomes much more appealing than listening to our mental chatter.\" — Sakyong Mipham Rinpoche",
  "\"When we commit ourselves to personal practice, life becomes an experience of unfolding wisdom, like the blossoming of a flower.\" — Sakyong Mipham Rinpoche",
  "\"A regular meditation practice has the power to connect us with our wakefulness, the spark of true success.\" — Sakyong Mipham Rinpoche",
  "\"Living as if aggression and desire are going to bring true success is like planting tomatoes when what we want is apples.\" — Sakyong Mipham Rinpoche",
  "\"If we want to be successful, we need to learn what our own mind is and how it works.\" — Sakyong Mipham Rinpoche",
  "\"In wishing for the happiness of others, we rise above attachment and aggression.\" — Sakyong Mipham Rinpoche",
  "\"Love and compassion are the basis of our consciousness. When we let them rule our lives, we achieve all our wishes.\" — Sakyong Mipham Rinpoche",
  "\"Through practice we discover our love and compassion and use it, instead of being used by negative elements that bring us down.\" — Sakyong Mipham Rinpoche",
  "\"Cheerfulness is an endless possibility that gives us the option of moving forward in any situation, instead of being oppressed by it.\" — Sakyong Mipham Rinpoche",
  "\"Without meditation as the bedrock of our day, how do we avoid being over-reactive, coerced by quick solutions to our problems?\" — Sakyong Mipham Rinpoche",
  "\"Asking outer conditions to make us okay will never bring success, because outer conditions are always changing.\" — Sakyong Mipham Rinpoche",
  "\"It is strange, but true—recognizing the ongoing and all-pervasive nature of suffering can take us toward satisfaction and success.\" — Sakyong Mipham Rinpoche",
  "\"Concern and compassion for the welfare of others is the source of our own happiness.\" — Sakyong Mipham Rinpoche",
  "\"We can outwit the cycle of suffering by investing our energy in the cause of lasting happiness, which is letting go of 'me.' This is how to be truly successful.\" — Sakyong Mipham Rinpoche",
  "\"If we can stabilize our motivation and learn to cultivate peace and compassion, we will be able to improve any environment.\" — Sakyong Mipham Rinpoche",
  "\"According to the basic laws of cause and effect, we must engage in virtuous activity to bring about true success—spiritual and worldly.\" — Sakyong Mipham Rinpoche",
  "\"If we help others—even think of helping others—we will quickly and effortlessly become successful.\" — Sakyong Mipham Rinpoche",
  "\"To think that anything besides virtue leads to success is swimming against the current of reality.\" — Sakyong Mipham Rinpoche",
  "\"Virtue is the only way to move forward in this life. If we aren't practicing virtue, we are either standing still or moving backwards.\" — Sakyong Mipham Rinpoche",
  "\"It doesn't matter if you're rich or poor—the determining factor of success and happiness is contentment.\" — Sakyong Mipham Rinpoche",
  "\"Every morning, we need to contemplate what we're doing today and how we will grow by benefiting those around us.\" — Sakyong Mipham Rinpoche",
  "\"Everything we need is already here. Acting from that realization is how we become successful.\" — Sakyong Mipham Rinpoche",
  "\"Caring for others is the basis of worldly success. This is the secret that we don't learn in school.\" — Sakyong Mipham Rinpoche",
  "\"Once we possess the wish-fulfilling jewel of wisdom and compassion, our life becomes blessed. Whatever we want happens without difficulty.\" — Sakyong Mipham Rinpoche",
  "\"Putting others first is how we begin to conquer agitation and raise windhorse, the ability to bring about success and happiness.\" — Sakyong Mipham Rinpoche",
  "\"When we sit in meditation, we're making a direct relationship to the source of happiness, this wish-fulfilling jewel, the mind itself.\" — Sakyong Mipham Rinpoche",
  "\"According to the tradition of Shambhala, being in the world can be the basis of spiritual success.\" — Sakyong Mipham Rinpoche",
  "\"The self-assured strength that grows from knowing that we already have what we need makes us gentle, because we are no longer desperate.\" — Sakyong Mipham Rinpoche",
  "\"All lasting happiness comes from wisdom and compassion.\" — Sakyong Mipham Rinpoche",
  "\"Real confidence and competence come acting for the benefit of everyone.\" — Sakyong Mipham Rinpoche",
  "\"If you want to be miserable, think about yourself. If you want to be happy, think of others.\" — Sakyong Mipham Rinpoche",
  "\"Compassion, patience, and nonattachment are considered virtues because they elevate us above negativity, leading to true happiness.\" — Sakyong Mipham Rinpoche",
  "\"Enlightened mind emerges whenever we wish for someone else's happiness without wanting anything in return.\" — Sakyong Mipham Rinpoche",
  "\"To encourage equanimity, imagine that everyone you encounter has been kind to you in the past.\" — Sakyong Mipham Rinpoche",
  "\"Generosity, patience, exertion, discipline, meditation, and prajna are the enlightened activities of the warrior bodhisattva.\" — Sakyong Mipham Rinpoche",
  "\"Continuously offering whatever you have with generosity enriches the discipline of nonattachment.\" — Sakyong Mipham Rinpoche",
  "\"Generosity dispels self-centeredness and the desire to consume.\" — Sakyong Mipham Rinpoche",
  "\"To increase patience, use discipline to keep your heart and mind open.\" — Sakyong Mipham Rinpoche",
  "\"The mind of meditation sharpens prajna, which sees things as they are.\" — Sakyong Mipham Rinpoche",
  "\"Bodhichitta is our lightest mind. It's light because it lacks the reference point of a self.\" — Sakyong Mipham Rinpoche",
  "\"The way to overcome self-obsession is to give without hesitation.\" — Sakyong Mipham Rinpoche",
  "\"Within the container of discipline, we can relax.\" — Sakyong Mipham Rinpoche",
  "\"Discipline looks at any situation and asks, 'What is the action? What is the result?'\" — Sakyong Mipham Rinpoche",
  "\"With discipline, we begin to understand how to maneuver in the realm of karma.\" — Sakyong Mipham Rinpoche",
  "\"Practicing patience, we overcome anger and aggression.\" — Sakyong Mipham Rinpoche",
  "\"Anger and aggression endanger the mind of enlightenment.\" — Sakyong Mipham Rinpoche",
  "\"When you feel angry, practice generating love and compassion on the spot.\" — Sakyong Mipham Rinpoche",
  "\"On the bodhisattva path, we practice making the mind bigger by stepping beyond ourselves.\" — Sakyong Mipham Rinpoche",
  "\"Prajna—seeing things as they are—is a gleaming sword that arises from meditation.\" — Sakyong Mipham Rinpoche",
  "\"To know the truth is to see the transitory nature of who we are—the selflessness of ourselves and others.\" — Sakyong Mipham Rinpoche",
  "\"To cross into the mind of enlightenment, move from thinking of yourself to considering another.\" — Sakyong Mipham Rinpoche",
  "\"Look at your thought, speech, and activity and ask, 'Is this taking me toward enlightenment or suffering?'\" — Sakyong Mipham Rinpoche",
  "\"One moment of anger can destroy a lot of positive actions, because it makes our mind hard.\" — Sakyong Mipham Rinpoche",
  "\"Patience is practical: it overcomes anger.\" — Sakyong Mipham Rinpoche",
  "\"Generosity can be as simple as saying something positive instead of something negative.\" — Sakyong Mipham Rinpoche",
  "\"When you run into someone, instead of thinking, 'Oh, there's so-and-so, still doing that same old thing,' try thinking, 'There goes the Buddha.'\" — Sakyong Mipham Rinpoche",
  "\"We're often so devoted to the concept of pleasure that we don't notice when the pleasure is turning into pain.\" — Sakyong Mipham Rinpoche",
  "\"If the mind is flexible, the world is flexible.\" — Sakyong Mipham Rinpoche",
  "\"When we decide to solve our problems by getting angry or greedy, we become trapped by those actions.\" — Sakyong Mipham Rinpoche",
  "\"Equanimity is not being untouched by the world, but letting go of fixed ideas.\" — Sakyong Mipham Rinpoche",
  "\"Contentment comes from knowing that everything it needs is contained in the present moment.\" — Sakyong Mipham Rinpoche",
  "\"Exerting yourself toward virtue creates stability in your life—happiness you can depend on.\" — Sakyong Mipham Rinpoche",
  "\"Letting go of attachment is the ultimate generosity, because it connects us with our wisdom and compassion.\" — Sakyong Mipham Rinpoche",
  "\"All activity is based upon the inspiration and motivation that's generated in our mind.\" — Sakyong Mipham Rinpoche",
  "\"The dharma asks, What is it we can gain that we can truly have? What can we strive for in life that will give us any ultimate return?\" — Sakyong Mipham Rinpoche",
  "\"Meditation isn't about being 'good.' It's about taming our mind by engaging our mind with proper motivation.\" — Sakyong Mipham Rinpoche",
  "\"With good motivation, at the end of the day we're different from the day before. That's why we call meditation a 'path.'\" — Sakyong Mipham Rinpoche",
  "\"The question, 'How does this benefit others?' widens our perspective, offering a barometer to discern what to cultivate and what to discard.\" — Sakyong Mipham Rinpoche",
  "\"Each time we rest in contentment, generate compassion, and let go of attachment, we are moving beyond the stress and confusion that keep us trapped in a shortsighted view.\" — Sakyong Mipham Rinpoche",
  "\"We can either crumble beneath unfortunate events, or we can use our powerful mind and rise above them.\" — Sakyong Mipham Rinpoche",
  "\"Every morning, we need to contemplate what we're doing in our life today and how we will grow by benefiting those around us.\" — Sakyong Mipham Rinpoche",
  "\"When our motivation is to make 'me' happy, the engines of our life run rough.\" — Sakyong Mipham Rinpoche",
  "\"Only when we have a plan for bringing meaning to our life will we make true progress.\" — Sakyong Mipham Rinpoche",
  "\"What makes our life spiritual or worldly is not our vocation, but our view.\" — Sakyong Mipham Rinpoche",
  "\"Knowing where we are, moving slowly, and determining our action carefully, we are stabilizing our strategy for bringing meaning to our life.\" — Sakyong Mipham Rinpoche",
  "\"To affect the karma of our life at this very moment, we can choose to act with virtue.\" — Sakyong Mipham Rinpoche",
  "\"Treading the path of virtue is how we can finally take control of our life.\" — Sakyong Mipham Rinpoche",
  "\"By knowing how our mind works, we can gather virtue and use karma to create peace and happiness, which eventually lead to freedom.\" — Sakyong Mipham Rinpoche",
  "\"The first step in expanding our motivation is to stop and notice what we're doing.\" — Sakyong Mipham Rinpoche",
  "\"What is your motivation for living? The more you contemplate motivation, the more potent and powerful a force it becomes.\" — Sakyong Mipham Rinpoche",
  "\"Contemplate your motivation in a brief ritual that begins your day. What's going on right now? What's propelling you?\" — Sakyong Mipham Rinpoche",
  "\"Our motivation is what paves the path from bewilderment and suffering to wisdom.\" — Sakyong Mipham Rinpoche",
  "\"To understand reality, we need a mind that is not overwhelmed by habitual patterns and has roused the motivation to be truly compassionate.\" — Sakyong Mipham Rinpoche",
  "\"In contemplating bodhichitta, we're molding our mind to the point where extending unconditional love and compassion is our basic motivation.\" — Sakyong Mipham Rinpoche",
  "\"When students asked the Buddha, How should I practice? the Buddha would answer, Bring virtue to whatever you are doing.\" — Sakyong Mipham Rinpoche",
  "\"Bringing the correct motivation to our practice involves taking time to feel gratitude for our good fortune.\" — Sakyong Mipham Rinpoche",
  "\"Steeping our mind in compassion every morning has the power to transform us throughout the day.\" — Sakyong Mipham Rinpoche",
  "\"It's important to be mindful of the environment, but what's more important is to be mindful of our attitude towards it.\" — Sakyong Mipham Rinpoche",
  "\"Without the proper motivation, we will not be able to hear the dharma.\" — Sakyong Mipham Rinpoche",
  "\"The way we orient the mind is called the path, an opportunity to direct our life, as well as its outcome.\" — Sakyong Mipham Rinpoche",
  "\"While living in stressful times does not ultimately affect our enlightened qualities, it does demand that we become more engaged in awakening them.\" — Sakyong Mipham Rinpoche",
  "\"How we orient our life is intimately connected with our motivation.\" — Sakyong Mipham Rinpoche",
  "\"When we wake up in the morning, where is our mind taking us? Whatever it is, from that motivation, everything else will arise.\" — Sakyong Mipham Rinpoche",
  "\"With a body made joyous through movement, the mind is able to relax.\" — Sakyong Mipham Rinpoche",
  "\"With mind/body balance, we can take the power of feeling good and generate compassion.\" — Sakyong Mipham Rinpoche",
  "\"In any kind of physical movement, we can synchronize mind and body, using the present moment as our gauge.\" — Sakyong Mipham Rinpoche",
  "\"True joy comes from knowing what you are doing, why you are doing it, and doing it wholeheartedly.\" — Sakyong Mipham Rinpoche",
  "\"Joy is obviously an experience of the mind, but it often begins with physical exhilaration.\" — Sakyong Mipham Rinpoche",
  "\"The more we move, the better we feel.\" — Sakyong Mipham Rinpoche",
  "\"By resting the mind on the breath we train in staying present and mindful.\" — Sakyong Mipham Rinpoche",
  "\"With meditation we become grounded in the experience of basic goodness. This leads us toward a healthy sense of self.\" — Sakyong Mipham Rinpoche",
  "\"Centering ourselves within a state of contentment is how we become totally happy.\" — Sakyong Mipham Rinpoche",
  "\"Cheerfulness helps move the mind forward.\" — Sakyong Mipham Rinpoche",
  "\"If we're ignoring our body, our mind has fewer possibilities to work with.\" — Sakyong Mipham Rinpoche",
  "\"A healthy body—and the ability to maintain it—demonstrates that we appreciate who we are and what we can do.\" — Sakyong Mipham Rinpoche",
  "\"True relaxation suggests a deep underlying confidence in our enlightened nature.\" — Sakyong Mipham Rinpoche",
  "\"Self-absorption depletes our life force; thinking of others enhances it.\" — Sakyong Mipham Rinpoche",
  "\"Gently coming back to the breath helps us appreciate who we are.\" — Sakyong Mipham Rinpoche",
  "\"At any moment we can slow down and remember that we're in a precious situation—the human realm.\" — Sakyong Mipham Rinpoche",
  "\"The future depends on what we do right now.\" — Sakyong Mipham Rinpoche",
  "\"Letting go of laziness and applying mindfulness takes courage.\" — Sakyong Mipham Rinpoche",
  "\"With the virtue of discipline, we are making a container in which we can grow.\" — Sakyong Mipham Rinpoche",
  "\"Letting go lets us soar into life instead of being oppressed by it.\" — Sakyong Mipham Rinpoche",
  "\"Without proper care and appreciation of this body, enlightenment becomes impossible.\" — Sakyong Mipham Rinpoche",
  "\"When our body is pliable, we have more control of our mind.\" — Sakyong Mipham Rinpoche",
  "\"Once we see how our mind works, we see how our life works.\" — Sakyong Mipham Rinpoche",
  "\"The one-pointed attention we cultivate in meditation gives us strength and focus in moving our body.\" — Sakyong Mipham Rinpoche",
  "\"Wanting to be anywhere but where we are, doing anything but what we're doing, is an unnecessary move that throws us off balance.\" — Sakyong Mipham Rinpoche",
  "\"When we ignore our body, we are not maintaining our vehicle.\" — Sakyong Mipham Rinpoche",
  "\"When we engage authentically with our body and mind, whatever we encounter becomes the Buddha saying, 'Just wake up!'\" — Sakyong Mipham Rinpoche",
  "\"In the posture of meditation, we embody fundamental health: grounded, balanced, and relaxed.\" — Sakyong Mipham Rinpoche",
  "\"Sitting meditation is a vacation from acting on the speed and vibration of the mind.\" — Sakyong Mipham Rinpoche",
  "\"Mindfulness engenders the patience and honesty to be self-aware.\" — Sakyong Mipham Rinpoche",
  "\"Mindfulness creates the psychological space in which to choose our responses off the cushion.\" — Sakyong Mipham Rinpoche",
  "\"Mindfulness gives us the confidence to be able to acknowledge our thoughts without being hooked by them.\" — Sakyong Mipham Rinpoche",
  "\"If we start each day with meditation, we are more prepared to face whatever arises.\" — Sakyong Mipham Rinpoche",
  "\"Learning to be present for the moment is the beginning of the spiritual path.\" — Sakyong Mipham Rinpoche",
  "\"Coming back to the breath is one of the most effective ways to work with fantasies and strong emotions.\" — Sakyong Mipham Rinpoche",
  "\"In meditation, mindfulness is what we use to hold our minds to the breath, and awareness is the intelligence that tells us what we're doing.\" — Sakyong Mipham Rinpoche",
  "\"True mindfulness is no separation between here and there.\" — Sakyong Mipham Rinpoche",
  "\"Cultivating mindfulness gives us the potential to have stronger, more focused access to whatever we are doing.\" — Sakyong Mipham Rinpoche",
  "\"Mindfulness and awareness present us with the revolutionary opportunity to observe the movement of the mind without being swept into it.\" — Sakyong Mipham Rinpoche",
  "\"Working steadily in meditation with the mind's wild chatter makes maintaining mindfulness throughout the day much easier.\" — Sakyong Mipham Rinpoche",
  "\"The fruition of peaceful abiding meditation is enduring mindfulness.\" — Sakyong Mipham Rinpoche",
  "\"With a mind that is able to focus in any endeavor, we feel centered and confident.\" — Sakyong Mipham Rinpoche",
  "\"Mindfulness shows us that at the basis of our being is something deeper and more open than fantasies, emotions, and discursiveness.\" — Sakyong Mipham Rinpoche",
  "\"By growing familiar with the feeling of a focused mind, we develop the strength to stay with it.\" — Sakyong Mipham Rinpoche",
  "\"Mindfulness engenders a clarity that connects us with reality.\" — Sakyong Mipham Rinpoche",
  "\"The Buddha taught that to wake up from the dream of bewilderment and suffering, we first need to sit still and take a deep breath.\" — Sakyong Mipham Rinpoche",
  "\"Samsara isn't a place, it's an attitude: 'I'm real and everything's for me.' With mindfulness we become aware of this attitude and begin to change it.\" — Sakyong Mipham Rinpoche",
  "\"If we're meditating properly, our practice and understanding will always take us a little further than we might think we want to go.\" — Sakyong Mipham Rinpoche",
  "\"With mindfulness, we see that samsara is a mistaken view that freezes reality into a concept.\" — Sakyong Mipham Rinpoche",
  "\"Speed is the enemy of mindfulness. The antidote is being appreciative and observant of life's every detail.\" — Sakyong Mipham Rinpoche",
  "\"Appreciating where we are and what we have, it is easy to relax on the spot.\" — Sakyong Mipham Rinpoche",
  "\"Appreciation creates a space that accommodates the daily vicissitudes and gives us room to think of others.\" — Sakyong Mipham Rinpoche",
  "\"As a way to appreciate everyone, regard all sentient beings as your mother.\" — Sakyong Mipham Rinpoche",
  "\"Appreciating your life relieves stress, brings joy, and has fantastic karmic repercussions.\" — Sakyong Mipham Rinpoche",
  "\"Change a small percentage of your attitude for a small percentage of the day. When you get up in the morning, say, 'With ten percent of my mind, I'm going to try appreciation.'\" — Sakyong Mipham Rinpoche",
  "\"Appreciation counteracts aggression.\" — Sakyong Mipham Rinpoche",
  "\"Every time you appreciate someone else, you are taking a vacation from the 'me' plan.\" — Sakyong Mipham Rinpoche",
  "\"Can we appreciate the fruits of meditation practice without expectation or attachment?\" — Sakyong Mipham Rinpoche",
  "\"Wherever you are, rest your mind in a sense of appreciation.\" — Sakyong Mipham Rinpoche",
  "\"The more we appreciate others, the softer and fertile our hearts become.\" — Sakyong Mipham Rinpoche",
  "\"Appreciation cuts through the clutter of negativity, revealing love and compassion, which are natural and permanent.\" — Sakyong Mipham Rinpoche",
  "\"Meditation shows us how to keep the mind in one place long enough to appreciate our surroundings.\" — Sakyong Mipham Rinpoche",
  "\"In order to overcome laziness, we need to be curious about life, combining appreciation with imagination.\" — Sakyong Mipham Rinpoche",
  "\"When we appreciate the preciousness of our life, we are less enmeshed in self-involvement.\" — Sakyong Mipham Rinpoche",
  "\"Appreciation invites us to tune in to simple and ordinary pleasures.\" — Sakyong Mipham Rinpoche",
  "\"When we appreciate what we have, being alive seems fresh and good.\" — Sakyong Mipham Rinpoche",
  "\"Appreciating your life makes problems seem smaller.\" — Sakyong Mipham Rinpoche",
  "\"Contemplating impermanence, we learn to appreciate the ebb and flow of life.\" — Sakyong Mipham Rinpoche",
  "\"Appreciating impermanence makes us less desperate people. We no longer try to squeeze out the last drop of pleasure; we no longer feel insulted by pain.\" — Sakyong Mipham Rinpoche",
  "\"Appreciate what you have, and utilize your insight to go beyond the boundaries of 'me.'\" — Sakyong Mipham Rinpoche",
  "\"We can slow down and feel fortunate to be here.\" — Sakyong Mipham Rinpoche",
  "\"At any moment of the day, we can rest our mind in an environment of appreciation and care.\" — Sakyong Mipham Rinpoche",
  "\"Appreciation comes from a mind that is much more able to appreciate, because it is content.\" — Sakyong Mipham Rinpoche",
  "\"Our hearts are cheerful when we appreciate our own wisdom.\" — Sakyong Mipham Rinpoche",
  "\"Learning to appreciate the peculiarities of life, we become more imaginative, able to find creative ways of uplifting ourselves.\" — Sakyong Mipham Rinpoche",
  "\"Can we appreciate something without trying to hold on to it?\" — Sakyong Mipham Rinpoche",
  "\"Wanting to possess something decreases our ability to see and appreciate what is there.\" — Sakyong Mipham Rinpoche",
  "\"Appreciate the richness of your life and develop it into a cadence and harmony that enriches others.\" — Sakyong Mipham Rinpoche",
  "\"Appreciate everybody and everything.\" — Sakyong Mipham Rinpoche",
  "\"We may think that we don't meditate, but we are always meditating on something, developing an attitude that builds the foundation for our actions.\" — Sakyong Mipham Rinpoche",
  "\"Meditation in action starts with slowing down, looking around, and appreciating our options.\" — Sakyong Mipham Rinpoche",
  "\"Our capacity to self-reflect gives us the power to take control of our mind.\" — Sakyong Mipham Rinpoche",
  "\"To determine whether an action is virtuous, ask: What is the result? Do I feel imprisoned or liberated? Do I have regret? Am I content?\" — Sakyong Mipham Rinpoche",
  "\"Sometimes life is quick, so you need to be quick; sometimes it's slow, so you need to be slow. With a nimble mind, you respond appropriately.\" — Sakyong Mipham Rinpoche",
  "\"If we expect somebody else to create peace in the world, we're going to be waiting for a long time.\" — Sakyong Mipham Rinpoche",
  "\"Only through discipline can we truly experience our vast mind, the outer limits of our possibilities.\" — Sakyong Mipham Rinpoche",
  "\"True love is not dependent on any one object.\" — Sakyong Mipham Rinpoche",
  "\"Regret is a symptom of trying to make 'me' happy.\" — Sakyong Mipham Rinpoche",
  "\"Resolving to help others takes our meditation into action.\" — Sakyong Mipham Rinpoche",
  "\"Negative emotions are signs of hope that the world will meet our expectations and fear that it will not.\" — Sakyong Mipham Rinpoche",
  "\"Dharma penetrates slowly, but if we are willing to stay with it, it will change us from the inside out.\" — Sakyong Mipham Rinpoche",
  "\"When we have gone beyond the boundaries of hope and fear, we are able to work with whatever comes our way.\" — Sakyong Mipham Rinpoche",
  "\"Prajna is called 'best knowledge' because it takes us toward experiencing reality directly, without concept.\" — Sakyong Mipham Rinpoche",
  "\"Open-mindedness and precision are the ingredients of meditation in action.\" — Sakyong Mipham Rinpoche",
  "\"Developing our patience, discipline, generosity, and exertion requires working with others.\" — Sakyong Mipham Rinpoche",
  "\"Meditation in action creates an environment in which our inherent happiness can flourish.\" — Sakyong Mipham Rinpoche",
  "\"Peaceful abiding gives us the potential to have stronger, more focused access to whatever we are doing.\" — Sakyong Mipham Rinpoche",
  "\"An emotion that feels as big as a house can be dismantled brick by brick. Start by asking, Where did this feeling come from? Where does it dwell?\" — Sakyong Mipham Rinpoche",
  "\"By contemplating a negative emotion, we weaken its power, which creates space. The coolness of reason dissipates the heat of the emotion.\" — Sakyong Mipham Rinpoche",
  "\"The missing spiritual evolutionary link is this: reaching into our heart and mind to determine our motivation, contemplating it, and then acting on it.\" — Sakyong Mipham Rinpoche",
  "\"It's important to be mindful of the environment, but what's more important is to be mindful of our attitude towards it—not having a lot of desire or fixation, knowing when we're moving from having had enough to excess.\" — Sakyong Mipham Rinpoche",
  "\"Practicing exertion helps us turn the tide of laziness.\" — Sakyong Mipham Rinpoche",
  "\"Through consistent practice, we grow familiar with the feeling of a focused mind. When we stay with it, this clarity connects us with reality.\" — Sakyong Mipham Rinpoche",
  "\"In the throes of an intense situation, contemplate the nature of samsara instead of blaming yourself or someone else. Samsara is not a place but a mistaken view, a way of freezing reality into a concept.\" — Sakyong Mipham Rinpoche",
  "\"Accepting impermanence means that we spend less energy resisting reality.\" — Sakyong Mipham Rinpoche",
  "\"If you use anger and desire to get what you want, and what you want is happiness, it's never going to work. Therefore contemplate your intention and actions.\" — Sakyong Mipham Rinpoche",
  "\"How many of us make time to generate love and compassion in our being?\" — Sakyong Mipham Rinpoche",
  "\"Every time we employ the qualities of generosity, patience, and equanimity, we are making our mind bigger.\" — Sakyong Mipham Rinpoche",
  "\"We can engage in life knowing what we're doing.\" — Sakyong Mipham Rinpoche",
  "\"Love is the inexhaustible resource of a settled mind.\" — Sakyong Mipham Rinpoche",
  "\"To change your life, change your attitude.\" — Sakyong Mipham Rinpoche",
  "\"If you feel regret at the end of the day, renew your intention to help others.\" — Sakyong Mipham Rinpoche",
  "\"Generating love enlarges your mind.\" — Sakyong Mipham Rinpoche",
  "\"Contemplating how to help others relieves stress.\" — Sakyong Mipham Rinpoche",
  "\"Thinking of others brings joy.\" — Sakyong Mipham Rinpoche",
  "\"Helping others has fantastic karmic repercussions.\" — Sakyong Mipham Rinpoche",
  "\"Make love your motivation.\" — Sakyong Mipham Rinpoche",
  "\"Use loving-kindness to counteract aggression, beginning with your own.\" — Sakyong Mipham Rinpoche",
  "\"Putting virtue into action improves any environment.\" — Sakyong Mipham Rinpoche",
  "\"Fear comes from not trusting our genuine being, which naturally radiates compassion and kindness.\" — Sakyong Mipham Rinpoche",
  "\"Fear comes from ignorance of who you really are.\" — Sakyong Mipham Rinpoche",
  "\"Appreciating where you are right now is a helpful antidote to depression.\" — Sakyong Mipham Rinpoche",
  "\"Practice creates an environment that supports us in changing our habits.\" — Sakyong Mipham Rinpoche",
  "\"Pay attention to your life.\" — Sakyong Mipham Rinpoche",
  "\"What environmental influences are you encouraging?\" — Sakyong Mipham Rinpoche",
  "\"As you live your day, where are you placing your mind?\" — Sakyong Mipham Rinpoche",
  "\"The basic antidote is mindfulness.\" — Sakyong Mipham Rinpoche",
  "\"With mindfulness, life's worldly aspects become part of your practice.\" — Sakyong Mipham Rinpoche",
  "\"Take charge of your day by using it to enhance your virtuous qualities.\" — Sakyong Mipham Rinpoche",
  "\"How do you determine what is virtuous? Look at the result.\" — Sakyong Mipham Rinpoche",
  "\"The mind that is directed toward others has achieved the most profound virtue.\" — Sakyong Mipham Rinpoche",
  "\"How can we be truly happy while others are suffering?\" — Sakyong Mipham Rinpoche",
  "\"Generating compassion is the most effective way to put meditation into action.\" — Sakyong Mipham Rinpoche",
  "\"Compassion lightens the mind and makes us nimble.\" — Sakyong Mipham Rinpoche",
  "\"All activity is based upon our motivation.\" — Sakyong Mipham Rinpoche",
  "\"To bring meaning to your life, determine each action carefully.\" — Sakyong Mipham Rinpoche",
  "\"What can we gain that we can truly have?\" — Sakyong Mipham Rinpoche",
  "\"We tame our mind by cultivating proper motivation.\" — Sakyong Mipham Rinpoche",
  "\"What can we strive for that will give us any ultimate return?\" — Sakyong Mipham Rinpoche",
  "\"To widen your perspective, ask, 'How does this benefit others?'\" — Sakyong Mipham Rinpoche",
  "\"To discern what to cultivate and what to discard, ask, 'How does this benefit others?'\" — Sakyong Mipham Rinpoche",
  "\"Stress traps us in a shortsighted view. To overcome it, rest in contentment.\" — Sakyong Mipham Rinpoche",
  "\"To move beyond confusion, generate compassion.\" — Sakyong Mipham Rinpoche",
  "\"Every morning, contemplate what you're doing today to benefit others.\" — Sakyong Mipham Rinpoche",
  "\"With the motivation to make 'me' happy, the engines of our life run rough.\" — Sakyong Mipham Rinpoche",
  "\"Only with a plan for bringing meaning to our life will we make true progress.\" — Sakyong Mipham Rinpoche",
  "\"What makes life spiritual or worldly is not our vocation, but our view.\" — Sakyong Mipham Rinpoche",
  "\"Know where you are and expand your motivation.\" — Sakyong Mipham Rinpoche",
  "\"To stabilize your strategy for bringing meaning to your life, move slowly.\" — Sakyong Mipham Rinpoche",
  "\"To change karma at this very moment, act with virtue.\" — Sakyong Mipham Rinpoche",
  "\"Take control of your life by treading the path of virtue.\" — Sakyong Mipham Rinpoche",
  "\"Expand your motivation—stop and notice what you're doing.\" — Sakyong Mipham Rinpoche",
  "\"What is your motivation for living?\" — Sakyong Mipham Rinpoche",
  "\"The more we contemplate motivation, the more powerful it becomes.\" — Sakyong Mipham Rinpoche",
  "\"Let love and compassion be your basic motivation.\" — Sakyong Mipham Rinpoche",
  "\"When we wake up in the morning, where does our mind go? From that motivation, everything will arise.\" — Sakyong Mipham Rinpoche",
  "\"What's going on right now? What's propelling you?\" — Sakyong Mipham Rinpoche",
  "\"By letting go of attachment, we move beyond the confusion that keeps us trapped in a small view.\" — Sakyong Mipham Rinpoche",
  "\"A mind steeped in compassion has the power to change the day.\" — Sakyong Mipham Rinpoche",
];
